# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: Jasper reports Grails Plugin
description: |
  Jasper reports plugin integrates jasper reports library with grails and makes it easy to generate 
  and render reports. Plugin also configures jasper spring mvc view resolver which makes it 
  possible to render views as reports easily from controllers.
author: Yak.Works
group: org.grails.plugins

github:
  fullName: yakworks/grails-jasper-reports

team:
  developers: ['basejump: Joshua Burnett']

bintray:
  enabled: true
  # user: ${findAnyProperty("BINTRAY_USER")} //uses System var property
  # key: ${props.findAny("BINTRAY_KEY")} //uses System var property
  pkg:
    repo: grails-plugins
    userOrg: 9ci

maven:
  # repoUrl: http://repo.9ci.com/grails-plugins
  snapshotUrl: http://repo.9ci.com/oss-snapshots

docs:
  enabled: false

releaseNotes:
  file: CHANGELOG.md
